
---
driver:
  name: vagrant
  customize:
    memory: 4096
  gui: false

driver_config:
  network:
  - ["forwarded_port", {guest: 8800, host: 8800}]
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 443, host: 8443}]

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: true

verifier:
  name: inspec
  ruby_bindir: '/usr/bin'

transport:
    max_ssh_sessions: 6
    
platforms:
  - name: bento/ubuntu-18.04
    provisioner:
      playbook: test/integration/default.yml
  - name: centos/7
    provisioner:
      playbook: test/integration/redhat.yml

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration