---

- name: terraform.d | Create terraform.d directory in /etc
  ansible.builtin.file:
    path: /etc/terraform.d
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: replicated.conf | Copy the replicated.conf template file
  ansible.builtin.template:
    src: replicated.conf.j2
    dest: /etc/replicated.conf
    mode: '0655'
    owner: root
    group: root

- name: settings.json | Create the replicated settings.json file in /etc/terraform.d
  ansible.builtin.template:
    src: settings.json.j2
    dest: /etc/terraform.d/settings.json
    mode: '0655'
    owner: root
    group: root

- name: install.sh | Download the Terraform Enterprise Installer
  ansible.builtin.get_url:
    url: https://install.terraform.io/ptfe/stable
    dest: /tmp/install.sh
    mode: '0777'
    owner: root
    group: root

- name: license.rli | Create the license file to be used for Terraform Enterprise
  ansible.builtin.copy:
    src: license.rli
    dest: /etc/terraform.d/license.rli
    mode: '0655'
    owner: root
    group: root

- name: install.sh | Execute the install.sh to install Terraform Enterprise
  ansible.builtin.shell: /tmp/install.sh no-proxy private-address={{ ansible_eth0.ipv4.address }} public-address={{ ansible_eth0.ipv4.address }}
  run_once: true
  register: result

- name: sleep | Finalize and wait for Terraform to come up
  ansible.builtin.shell: sleep 625
  when: result.changed

